// Code generated by protoc-gen-go. DO NOT EDIT.
// source: twitterProto1.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AddUserRequest struct {
	UName                string   `protobuf:"bytes,1,opt,name=UName,proto3" json:"UName,omitempty"`
	Pwd1                 string   `protobuf:"bytes,2,opt,name=pwd1,proto3" json:"pwd1,omitempty"`
	Pwd2                 string   `protobuf:"bytes,3,opt,name=pwd2,proto3" json:"pwd2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddUserRequest) Reset()         { *m = AddUserRequest{} }
func (m *AddUserRequest) String() string { return proto.CompactTextString(m) }
func (*AddUserRequest) ProtoMessage()    {}
func (*AddUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_931290a17477c411, []int{0}
}

func (m *AddUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddUserRequest.Unmarshal(m, b)
}
func (m *AddUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddUserRequest.Marshal(b, m, deterministic)
}
func (m *AddUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddUserRequest.Merge(m, src)
}
func (m *AddUserRequest) XXX_Size() int {
	return xxx_messageInfo_AddUserRequest.Size(m)
}
func (m *AddUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddUserRequest proto.InternalMessageInfo

func (m *AddUserRequest) GetUName() string {
	if m != nil {
		return m.UName
	}
	return ""
}

func (m *AddUserRequest) GetPwd1() string {
	if m != nil {
		return m.Pwd1
	}
	return ""
}

func (m *AddUserRequest) GetPwd2() string {
	if m != nil {
		return m.Pwd2
	}
	return ""
}

type BoolReply struct {
	T                    bool     `protobuf:"varint,1,opt,name=t,proto3" json:"t,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BoolReply) Reset()         { *m = BoolReply{} }
func (m *BoolReply) String() string { return proto.CompactTextString(m) }
func (*BoolReply) ProtoMessage()    {}
func (*BoolReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_931290a17477c411, []int{1}
}

func (m *BoolReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BoolReply.Unmarshal(m, b)
}
func (m *BoolReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BoolReply.Marshal(b, m, deterministic)
}
func (m *BoolReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BoolReply.Merge(m, src)
}
func (m *BoolReply) XXX_Size() int {
	return xxx_messageInfo_BoolReply.Size(m)
}
func (m *BoolReply) XXX_DiscardUnknown() {
	xxx_messageInfo_BoolReply.DiscardUnknown(m)
}

var xxx_messageInfo_BoolReply proto.InternalMessageInfo

func (m *BoolReply) GetT() bool {
	if m != nil {
		return m.T
	}
	return false
}

type UserExistsRequest struct {
	UName                string   `protobuf:"bytes,1,opt,name=UName,proto3" json:"UName,omitempty"`
	Pwd                  string   `protobuf:"bytes,2,opt,name=pwd,proto3" json:"pwd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserExistsRequest) Reset()         { *m = UserExistsRequest{} }
func (m *UserExistsRequest) String() string { return proto.CompactTextString(m) }
func (*UserExistsRequest) ProtoMessage()    {}
func (*UserExistsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_931290a17477c411, []int{2}
}

func (m *UserExistsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserExistsRequest.Unmarshal(m, b)
}
func (m *UserExistsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserExistsRequest.Marshal(b, m, deterministic)
}
func (m *UserExistsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserExistsRequest.Merge(m, src)
}
func (m *UserExistsRequest) XXX_Size() int {
	return xxx_messageInfo_UserExistsRequest.Size(m)
}
func (m *UserExistsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserExistsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserExistsRequest proto.InternalMessageInfo

func (m *UserExistsRequest) GetUName() string {
	if m != nil {
		return m.UName
	}
	return ""
}

func (m *UserExistsRequest) GetPwd() string {
	if m != nil {
		return m.Pwd
	}
	return ""
}

type Twitter_User struct {
	UName                string          `protobuf:"bytes,1,opt,name=UName,proto3" json:"UName,omitempty"`
	Pwd                  string          `protobuf:"bytes,2,opt,name=pwd,proto3" json:"pwd,omitempty"`
	Posts                []*TwitterPosts `protobuf:"bytes,3,rep,name=Posts,proto3" json:"Posts,omitempty"`
	Follow               []string        `protobuf:"bytes,4,rep,name=Follow,proto3" json:"Follow,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Twitter_User) Reset()         { *m = Twitter_User{} }
func (m *Twitter_User) String() string { return proto.CompactTextString(m) }
func (*Twitter_User) ProtoMessage()    {}
func (*Twitter_User) Descriptor() ([]byte, []int) {
	return fileDescriptor_931290a17477c411, []int{3}
}

func (m *Twitter_User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Twitter_User.Unmarshal(m, b)
}
func (m *Twitter_User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Twitter_User.Marshal(b, m, deterministic)
}
func (m *Twitter_User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Twitter_User.Merge(m, src)
}
func (m *Twitter_User) XXX_Size() int {
	return xxx_messageInfo_Twitter_User.Size(m)
}
func (m *Twitter_User) XXX_DiscardUnknown() {
	xxx_messageInfo_Twitter_User.DiscardUnknown(m)
}

var xxx_messageInfo_Twitter_User proto.InternalMessageInfo

func (m *Twitter_User) GetUName() string {
	if m != nil {
		return m.UName
	}
	return ""
}

func (m *Twitter_User) GetPwd() string {
	if m != nil {
		return m.Pwd
	}
	return ""
}

func (m *Twitter_User) GetPosts() []*TwitterPosts {
	if m != nil {
		return m.Posts
	}
	return nil
}

func (m *Twitter_User) GetFollow() []string {
	if m != nil {
		return m.Follow
	}
	return nil
}

type TwitterPosts struct {
	Contents             string   `protobuf:"bytes,1,opt,name=Contents,proto3" json:"Contents,omitempty"`
	Date                 int64    `protobuf:"varint,2,opt,name=Date,proto3" json:"Date,omitempty"`
	User                 string   `protobuf:"bytes,3,opt,name=User,proto3" json:"User,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TwitterPosts) Reset()         { *m = TwitterPosts{} }
func (m *TwitterPosts) String() string { return proto.CompactTextString(m) }
func (*TwitterPosts) ProtoMessage()    {}
func (*TwitterPosts) Descriptor() ([]byte, []int) {
	return fileDescriptor_931290a17477c411, []int{4}
}

func (m *TwitterPosts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TwitterPosts.Unmarshal(m, b)
}
func (m *TwitterPosts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TwitterPosts.Marshal(b, m, deterministic)
}
func (m *TwitterPosts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TwitterPosts.Merge(m, src)
}
func (m *TwitterPosts) XXX_Size() int {
	return xxx_messageInfo_TwitterPosts.Size(m)
}
func (m *TwitterPosts) XXX_DiscardUnknown() {
	xxx_messageInfo_TwitterPosts.DiscardUnknown(m)
}

var xxx_messageInfo_TwitterPosts proto.InternalMessageInfo

func (m *TwitterPosts) GetContents() string {
	if m != nil {
		return m.Contents
	}
	return ""
}

func (m *TwitterPosts) GetDate() int64 {
	if m != nil {
		return m.Date
	}
	return 0
}

func (m *TwitterPosts) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

type GetUserRequest struct {
	Uname                string   `protobuf:"bytes,1,opt,name=uname,proto3" json:"uname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_931290a17477c411, []int{5}
}

func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (m *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(m, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

func (m *GetUserRequest) GetUname() string {
	if m != nil {
		return m.Uname
	}
	return ""
}

type GetUserReply struct {
	Userinfo             *Twitter_User `protobuf:"bytes,1,opt,name=Userinfo,proto3" json:"Userinfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetUserReply) Reset()         { *m = GetUserReply{} }
func (m *GetUserReply) String() string { return proto.CompactTextString(m) }
func (*GetUserReply) ProtoMessage()    {}
func (*GetUserReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_931290a17477c411, []int{6}
}

func (m *GetUserReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserReply.Unmarshal(m, b)
}
func (m *GetUserReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserReply.Marshal(b, m, deterministic)
}
func (m *GetUserReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserReply.Merge(m, src)
}
func (m *GetUserReply) XXX_Size() int {
	return xxx_messageInfo_GetUserReply.Size(m)
}
func (m *GetUserReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserReply proto.InternalMessageInfo

func (m *GetUserReply) GetUserinfo() *Twitter_User {
	if m != nil {
		return m.Userinfo
	}
	return nil
}

type GetUserInfoRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserInfoRequest) Reset()         { *m = GetUserInfoRequest{} }
func (m *GetUserInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserInfoRequest) ProtoMessage()    {}
func (*GetUserInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_931290a17477c411, []int{7}
}

func (m *GetUserInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserInfoRequest.Unmarshal(m, b)
}
func (m *GetUserInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserInfoRequest.Marshal(b, m, deterministic)
}
func (m *GetUserInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserInfoRequest.Merge(m, src)
}
func (m *GetUserInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserInfoRequest.Size(m)
}
func (m *GetUserInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserInfoRequest proto.InternalMessageInfo

func (m *GetUserInfoRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type GetUserInfoReply struct {
	UName                string   `protobuf:"bytes,1,opt,name=uName,proto3" json:"uName,omitempty"`
	Unfollow             []string `protobuf:"bytes,2,rep,name=unfollow,proto3" json:"unfollow,omitempty"`
	Follow               []string `protobuf:"bytes,3,rep,name=Follow,proto3" json:"Follow,omitempty"`
	Posts                []string `protobuf:"bytes,4,rep,name=Posts,proto3" json:"Posts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserInfoReply) Reset()         { *m = GetUserInfoReply{} }
func (m *GetUserInfoReply) String() string { return proto.CompactTextString(m) }
func (*GetUserInfoReply) ProtoMessage()    {}
func (*GetUserInfoReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_931290a17477c411, []int{8}
}

func (m *GetUserInfoReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserInfoReply.Unmarshal(m, b)
}
func (m *GetUserInfoReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserInfoReply.Marshal(b, m, deterministic)
}
func (m *GetUserInfoReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserInfoReply.Merge(m, src)
}
func (m *GetUserInfoReply) XXX_Size() int {
	return xxx_messageInfo_GetUserInfoReply.Size(m)
}
func (m *GetUserInfoReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserInfoReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserInfoReply proto.InternalMessageInfo

func (m *GetUserInfoReply) GetUName() string {
	if m != nil {
		return m.UName
	}
	return ""
}

func (m *GetUserInfoReply) GetUnfollow() []string {
	if m != nil {
		return m.Unfollow
	}
	return nil
}

func (m *GetUserInfoReply) GetFollow() []string {
	if m != nil {
		return m.Follow
	}
	return nil
}

func (m *GetUserInfoReply) GetPosts() []string {
	if m != nil {
		return m.Posts
	}
	return nil
}

type Page struct {
	UName                string   `protobuf:"bytes,1,opt,name=uName,proto3" json:"uName,omitempty"`
	Unfollow             []string `protobuf:"bytes,2,rep,name=unfollow,proto3" json:"unfollow,omitempty"`
	Follow               []string `protobuf:"bytes,3,rep,name=follow,proto3" json:"follow,omitempty"`
	Posts                []string `protobuf:"bytes,4,rep,name=Posts,proto3" json:"Posts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Page) Reset()         { *m = Page{} }
func (m *Page) String() string { return proto.CompactTextString(m) }
func (*Page) ProtoMessage()    {}
func (*Page) Descriptor() ([]byte, []int) {
	return fileDescriptor_931290a17477c411, []int{9}
}

func (m *Page) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Page.Unmarshal(m, b)
}
func (m *Page) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Page.Marshal(b, m, deterministic)
}
func (m *Page) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Page.Merge(m, src)
}
func (m *Page) XXX_Size() int {
	return xxx_messageInfo_Page.Size(m)
}
func (m *Page) XXX_DiscardUnknown() {
	xxx_messageInfo_Page.DiscardUnknown(m)
}

var xxx_messageInfo_Page proto.InternalMessageInfo

func (m *Page) GetUName() string {
	if m != nil {
		return m.UName
	}
	return ""
}

func (m *Page) GetUnfollow() []string {
	if m != nil {
		return m.Unfollow
	}
	return nil
}

func (m *Page) GetFollow() []string {
	if m != nil {
		return m.Follow
	}
	return nil
}

func (m *Page) GetPosts() []string {
	if m != nil {
		return m.Posts
	}
	return nil
}

type GetUserInfo struct {
	Tweets               *Page    `protobuf:"bytes,1,opt,name=tweets,proto3" json:"tweets,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserInfo) Reset()         { *m = GetUserInfo{} }
func (m *GetUserInfo) String() string { return proto.CompactTextString(m) }
func (*GetUserInfo) ProtoMessage()    {}
func (*GetUserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_931290a17477c411, []int{10}
}

func (m *GetUserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserInfo.Unmarshal(m, b)
}
func (m *GetUserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserInfo.Marshal(b, m, deterministic)
}
func (m *GetUserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserInfo.Merge(m, src)
}
func (m *GetUserInfo) XXX_Size() int {
	return xxx_messageInfo_GetUserInfo.Size(m)
}
func (m *GetUserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserInfo proto.InternalMessageInfo

func (m *GetUserInfo) GetTweets() *Page {
	if m != nil {
		return m.Tweets
	}
	return nil
}

type FollowRequest struct {
	UName                string   `protobuf:"bytes,1,opt,name=uName,proto3" json:"uName,omitempty"`
	Othername            string   `protobuf:"bytes,2,opt,name=othername,proto3" json:"othername,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FollowRequest) Reset()         { *m = FollowRequest{} }
func (m *FollowRequest) String() string { return proto.CompactTextString(m) }
func (*FollowRequest) ProtoMessage()    {}
func (*FollowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_931290a17477c411, []int{11}
}

func (m *FollowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FollowRequest.Unmarshal(m, b)
}
func (m *FollowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FollowRequest.Marshal(b, m, deterministic)
}
func (m *FollowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FollowRequest.Merge(m, src)
}
func (m *FollowRequest) XXX_Size() int {
	return xxx_messageInfo_FollowRequest.Size(m)
}
func (m *FollowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FollowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FollowRequest proto.InternalMessageInfo

func (m *FollowRequest) GetUName() string {
	if m != nil {
		return m.UName
	}
	return ""
}

func (m *FollowRequest) GetOthername() string {
	if m != nil {
		return m.Othername
	}
	return ""
}

type TweetRequest struct {
	UName                string        `protobuf:"bytes,1,opt,name=uName,proto3" json:"uName,omitempty"`
	ProtoUser            *Twitter_User `protobuf:"bytes,2,opt,name=protoUser,proto3" json:"protoUser,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *TweetRequest) Reset()         { *m = TweetRequest{} }
func (m *TweetRequest) String() string { return proto.CompactTextString(m) }
func (*TweetRequest) ProtoMessage()    {}
func (*TweetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_931290a17477c411, []int{12}
}

func (m *TweetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TweetRequest.Unmarshal(m, b)
}
func (m *TweetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TweetRequest.Marshal(b, m, deterministic)
}
func (m *TweetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TweetRequest.Merge(m, src)
}
func (m *TweetRequest) XXX_Size() int {
	return xxx_messageInfo_TweetRequest.Size(m)
}
func (m *TweetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TweetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TweetRequest proto.InternalMessageInfo

func (m *TweetRequest) GetUName() string {
	if m != nil {
		return m.UName
	}
	return ""
}

func (m *TweetRequest) GetProtoUser() *Twitter_User {
	if m != nil {
		return m.ProtoUser
	}
	return nil
}

type IsLeaderRequest struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IsLeaderRequest) Reset()         { *m = IsLeaderRequest{} }
func (m *IsLeaderRequest) String() string { return proto.CompactTextString(m) }
func (*IsLeaderRequest) ProtoMessage()    {}
func (*IsLeaderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_931290a17477c411, []int{13}
}

func (m *IsLeaderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IsLeaderRequest.Unmarshal(m, b)
}
func (m *IsLeaderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IsLeaderRequest.Marshal(b, m, deterministic)
}
func (m *IsLeaderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IsLeaderRequest.Merge(m, src)
}
func (m *IsLeaderRequest) XXX_Size() int {
	return xxx_messageInfo_IsLeaderRequest.Size(m)
}
func (m *IsLeaderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IsLeaderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IsLeaderRequest proto.InternalMessageInfo

func (m *IsLeaderRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type JoinRequest struct {
	NodeID               string   `protobuf:"bytes,1,opt,name=nodeID,proto3" json:"nodeID,omitempty"`
	RemoteAddr           string   `protobuf:"bytes,2,opt,name=remoteAddr,proto3" json:"remoteAddr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinRequest) Reset()         { *m = JoinRequest{} }
func (m *JoinRequest) String() string { return proto.CompactTextString(m) }
func (*JoinRequest) ProtoMessage()    {}
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_931290a17477c411, []int{14}
}

func (m *JoinRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinRequest.Unmarshal(m, b)
}
func (m *JoinRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinRequest.Marshal(b, m, deterministic)
}
func (m *JoinRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinRequest.Merge(m, src)
}
func (m *JoinRequest) XXX_Size() int {
	return xxx_messageInfo_JoinRequest.Size(m)
}
func (m *JoinRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JoinRequest proto.InternalMessageInfo

func (m *JoinRequest) GetNodeID() string {
	if m != nil {
		return m.NodeID
	}
	return ""
}

func (m *JoinRequest) GetRemoteAddr() string {
	if m != nil {
		return m.RemoteAddr
	}
	return ""
}

func init() {
	proto.RegisterType((*AddUserRequest)(nil), "proto.AddUserRequest")
	proto.RegisterType((*BoolReply)(nil), "proto.BoolReply")
	proto.RegisterType((*UserExistsRequest)(nil), "proto.UserExistsRequest")
	proto.RegisterType((*Twitter_User)(nil), "proto.Twitter_User")
	proto.RegisterType((*TwitterPosts)(nil), "proto.TwitterPosts")
	proto.RegisterType((*GetUserRequest)(nil), "proto.GetUserRequest")
	proto.RegisterType((*GetUserReply)(nil), "proto.GetUserReply")
	proto.RegisterType((*GetUserInfoRequest)(nil), "proto.GetUserInfoRequest")
	proto.RegisterType((*GetUserInfoReply)(nil), "proto.GetUserInfoReply")
	proto.RegisterType((*Page)(nil), "proto.Page")
	proto.RegisterType((*GetUserInfo)(nil), "proto.GetUserInfo")
	proto.RegisterType((*FollowRequest)(nil), "proto.FollowRequest")
	proto.RegisterType((*TweetRequest)(nil), "proto.TweetRequest")
	proto.RegisterType((*IsLeaderRequest)(nil), "proto.IsLeaderRequest")
	proto.RegisterType((*JoinRequest)(nil), "proto.JoinRequest")
}

func init() { proto.RegisterFile("twitterProto1.proto", fileDescriptor_931290a17477c411) }

var fileDescriptor_931290a17477c411 = []byte{
	// 639 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0x5b, 0x6f, 0xd3, 0x4c,
	0x10, 0xfd, 0x52, 0x27, 0xa9, 0x33, 0xe9, 0x57, 0xc2, 0x16, 0x8a, 0x1b, 0x55, 0xa8, 0x5a, 0x24,
	0x54, 0x84, 0x64, 0x5a, 0x53, 0x81, 0x04, 0x0f, 0xa8, 0x4d, 0x0b, 0x0a, 0x42, 0x55, 0x64, 0x11,
	0xf5, 0xb1, 0x72, 0xf0, 0x38, 0x44, 0x4a, 0xbc, 0xc6, 0xde, 0xc8, 0xed, 0x4f, 0xe7, 0x0d, 0xed,
	0xc5, 0xb7, 0xc4, 0x44, 0xc0, 0x53, 0x76, 0x66, 0xcf, 0xce, 0x99, 0x3d, 0x73, 0xb2, 0x86, 0x3d,
	0x9e, 0xce, 0x38, 0xc7, 0x78, 0x14, 0x33, 0xce, 0x4e, 0xed, 0x48, 0xfc, 0x90, 0x96, 0xfc, 0xa1,
	0xd7, 0xb0, 0x7b, 0xee, 0xfb, 0xe3, 0x04, 0x63, 0x17, 0x7f, 0x2c, 0x31, 0xe1, 0xe4, 0x11, 0xb4,
	0xc6, 0xd7, 0xde, 0x02, 0xad, 0xc6, 0x51, 0xe3, 0xb8, 0xe3, 0xaa, 0x80, 0x10, 0x68, 0x46, 0xa9,
	0x7f, 0x6a, 0x6d, 0xc9, 0xa4, 0x5c, 0xeb, 0x9c, 0x63, 0x19, 0x79, 0xce, 0xa1, 0x07, 0xd0, 0xb9,
	0x60, 0x6c, 0xee, 0x62, 0x34, 0xbf, 0x27, 0x3b, 0xd0, 0xe0, 0xb2, 0x8c, 0xe9, 0x36, 0x38, 0x7d,
	0x0f, 0x0f, 0x05, 0xcf, 0xd5, 0xdd, 0x2c, 0xe1, 0xc9, 0x66, 0xb6, 0x1e, 0x18, 0x51, 0xea, 0x6b,
	0x32, 0xb1, 0xa4, 0xf7, 0xb0, 0xf3, 0x55, 0xdd, 0xe2, 0x56, 0x14, 0xf9, 0xd3, 0x73, 0xe4, 0x05,
	0xb4, 0x46, 0x2c, 0xe1, 0x89, 0x65, 0x1c, 0x19, 0xc7, 0x5d, 0x67, 0x4f, 0xdd, 0xde, 0xd6, 0xb5,
	0xe4, 0x96, 0xab, 0x10, 0x64, 0x1f, 0xda, 0x1f, 0xd9, 0x7c, 0xce, 0x52, 0xab, 0x79, 0x64, 0x1c,
	0x77, 0x5c, 0x1d, 0x51, 0x37, 0xa7, 0x56, 0xb8, 0x3e, 0x98, 0x03, 0x16, 0x72, 0x0c, 0x79, 0xa2,
	0xd9, 0xf3, 0x58, 0x48, 0x72, 0xe9, 0x71, 0x94, 0x1d, 0x18, 0xae, 0x5c, 0x8b, 0x9c, 0x68, 0x39,
	0x93, 0x49, 0xac, 0xe9, 0x73, 0xd8, 0xfd, 0x84, 0x7c, 0x45, 0xf6, 0x65, 0x58, 0xba, 0x90, 0x0c,
	0xe8, 0x07, 0xd8, 0xc9, 0x71, 0x42, 0xd1, 0x57, 0x60, 0x8a, 0x60, 0x16, 0x06, 0x4c, 0x02, 0xd7,
	0x6e, 0x24, 0xd5, 0x71, 0x73, 0x10, 0x3d, 0x01, 0xa2, 0x0b, 0x0c, 0xc3, 0x80, 0x65, 0x64, 0x7d,
	0x30, 0x97, 0x09, 0xc6, 0x25, 0xbe, 0x3c, 0xa6, 0x31, 0xf4, 0x2a, 0x27, 0x04, 0xad, 0x68, 0xae,
	0xac, 0xb6, 0x0c, 0x64, 0x95, 0x30, 0x50, 0x92, 0x6d, 0x49, 0xc9, 0xf2, 0xb8, 0x24, 0xa6, 0x51,
	0x16, 0x53, 0x54, 0x52, 0xf3, 0x50, 0x1a, 0xab, 0x80, 0x06, 0xd0, 0x1c, 0x79, 0x53, 0xfc, 0x37,
	0x9e, 0xa0, 0xc2, 0x13, 0x6c, 0xe2, 0x71, 0xa0, 0x5b, 0xba, 0x1b, 0x79, 0x06, 0x6d, 0x9e, 0x22,
	0xea, 0x39, 0x76, 0x9d, 0xae, 0xd6, 0x52, 0xf4, 0xe2, 0xea, 0x2d, 0x3a, 0x80, 0xff, 0x55, 0xef,
	0xe5, 0x49, 0xad, 0x37, 0x79, 0x08, 0x1d, 0xc6, 0xbf, 0x6b, 0x4d, 0x95, 0x01, 0x8b, 0x04, 0xbd,
	0x11, 0x1e, 0x42, 0xe4, 0x9b, 0x6b, 0x9c, 0x42, 0x47, 0x36, 0x20, 0xed, 0xb2, 0xf5, 0xfb, 0xf1,
	0x16, 0x28, 0xfa, 0x12, 0x1e, 0x0c, 0x93, 0x2f, 0xe8, 0xf9, 0x85, 0x93, 0x2c, 0xd8, 0xf6, 0x7c,
	0x3f, 0xc6, 0x24, 0xb3, 0x67, 0x16, 0xd2, 0x2b, 0xe8, 0x7e, 0x66, 0xb3, 0x30, 0x03, 0xee, 0x43,
	0x3b, 0x64, 0x3e, 0x0e, 0x2f, 0x35, 0x4e, 0x47, 0xe4, 0x29, 0x40, 0x8c, 0x0b, 0xc6, 0xf1, 0xdc,
	0xf7, 0x63, 0x7d, 0x97, 0x52, 0xc6, 0xf9, 0x69, 0x80, 0x71, 0x83, 0x13, 0x72, 0x06, 0xdb, 0xfa,
	0xed, 0x20, 0x8f, 0x75, 0x9b, 0xd5, 0xb7, 0xa4, 0xdf, 0xd3, 0xe9, 0xfc, 0x49, 0xa0, 0xff, 0x91,
	0x77, 0x00, 0xc5, 0x33, 0x40, 0x2c, 0x8d, 0x58, 0x7b, 0x19, 0x6a, 0xcf, 0xbe, 0x85, 0x6d, 0x3d,
	0xbf, 0x9c, 0xb1, 0xfa, 0x37, 0xea, 0xef, 0xad, 0xa6, 0xd5, 0xc1, 0x41, 0x75, 0xf0, 0x07, 0x55,
	0x54, 0xe9, 0xaf, 0xd1, 0x7f, 0x52, 0xb7, 0xa5, 0x8a, 0x38, 0x90, 0xbb, 0x58, 0x83, 0x2a, 0xc6,
	0xa8, 0xed, 0xf8, 0x04, 0x5a, 0x72, 0xf0, 0xa4, 0x18, 0x64, 0x61, 0x83, 0xda, 0x13, 0x67, 0x60,
	0x8e, 0xc3, 0xbf, 0xe6, 0x79, 0x03, 0x66, 0xe6, 0x03, 0xb2, 0xaf, 0xf7, 0x57, 0x8c, 0x51, 0x7b,
	0xce, 0x86, 0xa6, 0xb0, 0x04, 0x21, 0x7a, 0xaf, 0xe4, 0x8f, 0x3a, 0xfc, 0x85, 0x03, 0x87, 0x33,
	0x66, 0x4f, 0xe3, 0xe8, 0x9b, 0x8d, 0x77, 0xde, 0x22, 0x9a, 0x63, 0x62, 0xeb, 0xcf, 0xcb, 0x6d,
	0x8a, 0x93, 0x8b, 0x5e, 0xf6, 0x54, 0x7a, 0x53, 0x94, 0xdf, 0x9b, 0x51, 0x63, 0xd2, 0x96, 0x65,
	0x5e, 0xff, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x57, 0xba, 0xb6, 0x84, 0x88, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WebClient is the client API for Web service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WebClient interface {
	AddUser(ctx context.Context, in *AddUserRequest, opts ...grpc.CallOption) (*BoolReply, error)
	UserExists(ctx context.Context, in *UserExistsRequest, opts ...grpc.CallOption) (*BoolReply, error)
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserReply, error)
	GetUserInfo(ctx context.Context, in *GetUserInfoRequest, opts ...grpc.CallOption) (*GetUserInfoReply, error)
	Follow(ctx context.Context, in *FollowRequest, opts ...grpc.CallOption) (*BoolReply, error)
	Tweet(ctx context.Context, in *TweetRequest, opts ...grpc.CallOption) (*BoolReply, error)
	UnFollow(ctx context.Context, in *FollowRequest, opts ...grpc.CallOption) (*BoolReply, error)
	IsLeader(ctx context.Context, in *IsLeaderRequest, opts ...grpc.CallOption) (*BoolReply, error)
	Join(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*BoolReply, error)
}

type webClient struct {
	cc *grpc.ClientConn
}

func NewWebClient(cc *grpc.ClientConn) WebClient {
	return &webClient{cc}
}

func (c *webClient) AddUser(ctx context.Context, in *AddUserRequest, opts ...grpc.CallOption) (*BoolReply, error) {
	out := new(BoolReply)
	err := c.cc.Invoke(ctx, "/proto.Web/AddUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webClient) UserExists(ctx context.Context, in *UserExistsRequest, opts ...grpc.CallOption) (*BoolReply, error) {
	out := new(BoolReply)
	err := c.cc.Invoke(ctx, "/proto.Web/UserExists", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserReply, error) {
	out := new(GetUserReply)
	err := c.cc.Invoke(ctx, "/proto.Web/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webClient) GetUserInfo(ctx context.Context, in *GetUserInfoRequest, opts ...grpc.CallOption) (*GetUserInfoReply, error) {
	out := new(GetUserInfoReply)
	err := c.cc.Invoke(ctx, "/proto.Web/GetUserInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webClient) Follow(ctx context.Context, in *FollowRequest, opts ...grpc.CallOption) (*BoolReply, error) {
	out := new(BoolReply)
	err := c.cc.Invoke(ctx, "/proto.Web/Follow", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webClient) Tweet(ctx context.Context, in *TweetRequest, opts ...grpc.CallOption) (*BoolReply, error) {
	out := new(BoolReply)
	err := c.cc.Invoke(ctx, "/proto.Web/Tweet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webClient) UnFollow(ctx context.Context, in *FollowRequest, opts ...grpc.CallOption) (*BoolReply, error) {
	out := new(BoolReply)
	err := c.cc.Invoke(ctx, "/proto.Web/UnFollow", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webClient) IsLeader(ctx context.Context, in *IsLeaderRequest, opts ...grpc.CallOption) (*BoolReply, error) {
	out := new(BoolReply)
	err := c.cc.Invoke(ctx, "/proto.Web/IsLeader", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webClient) Join(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*BoolReply, error) {
	out := new(BoolReply)
	err := c.cc.Invoke(ctx, "/proto.Web/Join", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WebServer is the server API for Web service.
type WebServer interface {
	AddUser(context.Context, *AddUserRequest) (*BoolReply, error)
	UserExists(context.Context, *UserExistsRequest) (*BoolReply, error)
	GetUser(context.Context, *GetUserRequest) (*GetUserReply, error)
	GetUserInfo(context.Context, *GetUserInfoRequest) (*GetUserInfoReply, error)
	Follow(context.Context, *FollowRequest) (*BoolReply, error)
	Tweet(context.Context, *TweetRequest) (*BoolReply, error)
	UnFollow(context.Context, *FollowRequest) (*BoolReply, error)
	IsLeader(context.Context, *IsLeaderRequest) (*BoolReply, error)
	Join(context.Context, *JoinRequest) (*BoolReply, error)
}

func RegisterWebServer(s *grpc.Server, srv WebServer) {
	s.RegisterService(&_Web_serviceDesc, srv)
}

func _Web_AddUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebServer).AddUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Web/AddUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebServer).AddUser(ctx, req.(*AddUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Web_UserExists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserExistsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebServer).UserExists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Web/UserExists",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebServer).UserExists(ctx, req.(*UserExistsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Web_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Web/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Web_GetUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebServer).GetUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Web/GetUserInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebServer).GetUserInfo(ctx, req.(*GetUserInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Web_Follow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FollowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebServer).Follow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Web/Follow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebServer).Follow(ctx, req.(*FollowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Web_Tweet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TweetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebServer).Tweet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Web/Tweet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebServer).Tweet(ctx, req.(*TweetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Web_UnFollow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FollowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebServer).UnFollow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Web/UnFollow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebServer).UnFollow(ctx, req.(*FollowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Web_IsLeader_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsLeaderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebServer).IsLeader(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Web/IsLeader",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebServer).IsLeader(ctx, req.(*IsLeaderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Web_Join_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebServer).Join(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Web/Join",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebServer).Join(ctx, req.(*JoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Web_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Web",
	HandlerType: (*WebServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddUser",
			Handler:    _Web_AddUser_Handler,
		},
		{
			MethodName: "UserExists",
			Handler:    _Web_UserExists_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _Web_GetUser_Handler,
		},
		{
			MethodName: "GetUserInfo",
			Handler:    _Web_GetUserInfo_Handler,
		},
		{
			MethodName: "Follow",
			Handler:    _Web_Follow_Handler,
		},
		{
			MethodName: "Tweet",
			Handler:    _Web_Tweet_Handler,
		},
		{
			MethodName: "UnFollow",
			Handler:    _Web_UnFollow_Handler,
		},
		{
			MethodName: "IsLeader",
			Handler:    _Web_IsLeader_Handler,
		},
		{
			MethodName: "Join",
			Handler:    _Web_Join_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "twitterProto1.proto",
}
